# Generated by Django 2.1.7 on 2019-11-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_1', to='aqi.Aqi')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_2', to='aqi.Aqi')),
            ],
        ),
    ]
